<table>
    <tr>
        <td colspan="14" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:20px; font-weight:bold;" colspan="7"
            rowspan="1">
            Payment Voucher Report
            <br>
          Party Name : {{   $partyname['party_status']->name }}<br>
          Party Type : {{   $partyname['type'] }}
          

        </td>
     
        <td style="background-color: {{$color}}; color:white; padding-top:10px;" colspan="7" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
            Report Period : {{ $start_date }} - {{ $end_date }}

        </td>


    </tr>


    <tr>
        <td colspan="14" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:17px; font-weight:bold;" colspan="14"
            rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="14" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="14" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="14" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">#</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Date</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Voucher No.</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Company</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Site</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Amount</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Status</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Created By</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Approved By</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Paid By</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Payment Details</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Payment Date</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Remark</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Image/s</th>
    </tr>
    @php
        $count = 0;
    @endphp
    @foreach ($data as $dat)
        <tr>
            <td>{{ ++$count }}</td>
            <td>{{ $dat->date }}</td>
            <td>{{ $dat->voucher_no }}</td>
            <td>{{ $dat->company_name }}</td>
            <td>{{ $dat->site_name }}</td>
            <td  style="font-weight:bold;" >{{ $dat->amount }}</td>
            @if ($dat->status == 'Pending')
                <td style="color:orange;">{{ $dat->status }}</td>
            @elseif($dat->status == 'Rejected')
                <td style="color:red;">{{ $dat->status }}</td>
            @elseif($dat->status == 'Approved')
                <td style="color:blue;">{{ $dat->status }}</td>
            @elseif($dat->status == 'Paid')
                <td style="color:green;">{{ $dat->status }}</td>
            @endif
            <td>{{ $dat->created_user }}</td>
            <td>{{ $dat->approved_user }}</td>
            <td>{{ $dat->paid_user }}</td>
            <td>{{ $dat->payment_details }}</td>
            <td>{{ $dat->payment_date }}</td>
            <td>{{ $dat->remark }}</td>



            <td>
                @if ($dat->image != null)
                    <a href="<?= attachmentUrl($dat->image) ?>">View Image</a>
                @endif
                @if ($dat->payment_image != null)
                    <a href="<?= attachmentUrl($dat->payment_image) ?>">View Payment Image</a>
                @endif
            </td>

        
        </tr>
    @endforeach
</table>
