<table>
    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:20px; font-weight:bold;" colspan="5"
            rowspan="1">
            Machinery Sale Report
         


        </td>
     
        <td style="background-color: {{ $color }}; color:white; padding-top:10px;" colspan="5" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
         
            Report Period : {{ $start_date }} - {{ $end_date }}
        </td>


    </tr>


    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:17px; font-weight:bold;"
            colspan="10" rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="10" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="10" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th colspan="2" style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Date</th>
        <th colspan="2" style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Name</th>
        <th colspan="2" style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Head Name</th>
            <th colspan="2" style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
                Sale Site</th>
      
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Amount</th>
          </tr>
    @php
        $count = 0;
    @endphp
    @foreach ($data as $dat)
        <tr>
            <td>{{ ++$count }}</td>
            <td colspan="2">{{ $dat->sale_date }}</td>
            <td colspan="2">{{ $dat->name }}</td>
            <td colspan="2">{{ $dat->head_name }}</td>
            <td colspan="2">{{ $dat->sale_site }}</td>

            <td>{{ $dat->sale_price }}</td>

        </tr>
    @endforeach
</table>
