<table>
    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:20px; font-weight:bold;" colspan="5"
            rowspan="1">
            Machinery Purchase Report
            <br>
            Report Period : {{ $start_date }} - {{ $end_date }}


        </td>
        <td style="background-color: {{ $color }}; color:white;"colspan="1" rowspan="1">

        </td>
        <td style="background-color: {{ $color }}; color:white; padding-top:10px;" colspan="4" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
           

        </td>


    </tr>


    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:17px; font-weight:bold;"
            colspan="10" rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="10" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="10" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Date</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Name</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Head</th>
            <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
                Purchase Site</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Party Name</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            User</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Amount</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Status</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Current Site</th>
    </tr>
    @php
        $count = 0;
    @endphp
    @foreach ($data as $dat)
        <tr>
            <td>{{ ++$count }}</td>
            <td>{{ $dat->date }}</td>
            <td>{{ $dat->name }}</td>
            <td>{{ $dat->head_name }}</td>
            <td>{{ $dat->purchase_site }}</td>
            <td>{{ $dat->party_name }}</td>
            <td>{{ $dat->user_name }}</td>
            <td style="font-weight:bold;">{{ $dat->cost_price }}</td>



            @if ($dat->status == 'Working')
                <td style="color:green;">{{ $dat->status }}</td>
            @elseif($dat->status == 'Sold')
                <td style="color:red;">
                    {{ $dat->status }}
                    <br>
                    Sold Price - {{ $dat->sale_price }}
                </td>
            @else
            <td style="color:orange;">{{ $dat->status }}</td>
            @endif
            <td>{{ $dat->working_site }}</td>

        </tr>
    @endforeach
</table>
