<table>
    <tr>
        <td colspan="13" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:20px; font-weight:bold;" colspan="7"
            rowspan="1">
            Machinery Service Report
            <br>



        </td>

        <td style="background-color: {{ $color }}; color:white; padding-top:10px;" colspan="6" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
            Report Period : {{ $start_date }} - {{ $end_date }}

        </td>


    </tr>


    <tr>
        <td colspan="13" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:17px; font-weight:bold;"
            colspan="13" rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="13" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="13" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="13" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Name</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Head</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Date</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            User</th>

        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Maintenance Items</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Next Service</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Remark</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Attachment 1</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Attachment 2</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Attachment 3</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Attachment 4</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Attachment 5</th>

    </tr>
    @php
        $count = 0;
    @endphp
    @if (count($data) > 0)
        @php
            $machine = $data[0]->machinery_id;
        @endphp
        @foreach ($data as $dat)
            @if ($dat->machinery_id != $machine)
                @php $machine=$dat->machinery_id; @endphp
                <tr>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>

                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                    <td style="background-color:black;"></td>
                </tr>
            @endif
            <tr>
                <td>{{ ++$count }}</td>
                <td>{{ $dat->machine_name }}</td>
                <td>{{ $dat->head_name }}</td>
                <td>{{ $dat->create_date }}</td>
                <td>{{ $dat->user_name }}</td>
                <td>{{ $dat->maintainence_item }}</td>
                <td>{{ $dat->next_service_on }}</td>
                <td>{{ $dat->remark }}</td>
                <td>
                    @if($dat->image1 != "N/A")                    
                    <a href="<?= attachmentUrl($dat->image1) ?>">View Attachment</a>
                @endif
                </td>

                <td>
                    @if($dat->image2 != "N/A")                    
                    <a href="<?= attachmentUrl($dat->image2) ?>">View Attachment</a>
                @endif
                </td>


                <td>
                    @if($dat->image3 != "N/A")                    
                    <a href="<?= attachmentUrl($dat->image3) ?>">View Attachment</a>
                @endif
                </td>

                <td>
                    @if($dat->image4 != "N/A")                    
                    <a href="<?= attachmentUrl($dat->image4) ?>">View Attachment</a>
                @endif
                </td>

                <td>
                    @if($dat->image5 != "N/A")                    
                    <a href="<?= attachmentUrl($dat->image5) ?>">View Attachment</a>
                @endif
                </td>

            </tr>
        @endforeach
    @endif
</table>
