<table>
    <tr>
        <td colspan="8" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:20px; font-weight:bold;" colspan="4"
            rowspan="1">
            Machinery Document Report
            <br>
            Head Name : {{ $headname }}


        </td>
   
        <td style="background-color: {{ $color }}; color:white; padding-top:10px;" colspan="4" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
            Report Period : {{ $start_date }} - {{ $end_date }}

        </td>


    </tr>


    <tr>
        <td colspan="8" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:17px; font-weight:bold;"
            colspan="8" rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="8" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="8" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="8" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Name</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Date</th>
    
        <th   style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Document</th>
        <th   style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Issue Date</th>
            <th   style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
                End Date</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Attachment</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Remark</th>
       
    </tr>
    @php
        $count = 0;
    @endphp
    @if(count($data)>0)
      @php
      $machine=$data[0]->machinery_id;
    @endphp
    @foreach ($data as $dat)
    @if($dat->machinery_id != $machine)
    @php $machine=$dat->machinery_id; @endphp
    <tr>
      <td style="background-color:black;"></td>
      <td style="background-color:black;"></td>
      <td style="background-color:black;"></td>
      <td    style="background-color:black;"></td>
      <td   style="background-color:black;"></td>
      <td style="background-color:black;"></td>
      <td style="background-color:black;"></td>
      <td style="background-color:black;"></td>
    </tr>
    @endif
        <tr>
            <td>{{ ++$count }}</td>
            <td>{{ $dat->machine_name }}</td>
            <td>{{ $dat->create_date }}</td>
            <td   >{{ $dat->name }}</td>
            <td   >{{ $dat->issue_date }}</td>
            <td   >{{ $dat->end_date }}</td>
            <td><a href="<?= attachmentUrl($dat->attachment) ?>">View Attachment</a></td>       
            <td >{{ $dat->remark }}</td>
        </tr>
    @endforeach
    @endif
</table>
