<html>

<head>
    <style>
        .sub {
            display: flex;
            /* align-items: center; */
            justify-content: space-between;
            color: white;
            place-content: space-between;
        }

        .half-div {
            margin-left: 20px;
            margin-right: 20px;
            width: 40%;
            display: inline-block;
            vertical-align: top;
        }


        h4,
        h6 {
            margin: 0;
        }

        .row {
            display: flex;
            justify-content: space-between;
            border-bottom: 1px solid #ccc;
            padding: 8px 0;
        }

        .header {
            font-weight: bold;
        }




        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
            padding-bottom: 30px;

        }

        #customers td,
        #customers th {
            border: 1.5px solid black;
            font-size: 6px;
            padding: 8px;
        }


        #customers th {

            padding-top: 12px;
            padding-bottom: 12px;
            text-align: center;

            color: white;
        }

        .tmain {
            background-color: white;
            margin: 10px;

            padding: 2px;
            border-radius: 25px;
        }

        .hmain {
            color: white;
            font-size: 25px;
            margin-top: -20px;
        }

        h3 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        hr {
            height: 1.5px;
            width: 90%;
            background-color: black;
            margin-bottom: 30px;

        }
    </style>
</head>

<body style="background-color:{{ session()->get('primary_color')[0] }}; border-radius: 25px;">



    <div class="hmain">
        <h3 style="font-size:40px;">Bills Report</h3>

        <p style="margin-top:-30px;">Party Name : {{ $partyname }}</p>
        <p style="margin-top:-30px;">Report Period : {{ $start_date }} - {{ $end_date }}</p>
        <div class="sub">
            <div class="half-div" style="float:left;">
                <h6>Report Generated From </h6>
                <h4><u><a href="https://constructionmunshi.com/" target="_blank" style="color:white;">Construction
                            Munshi</a></u></h4>

            </div>
            <div class="half-div" style="float:right;">
                <h6>Report Generated On: <?= date('d-m-Y') ?> </h6>
                <h6>Report Generated By: <?= session('name') ?> </h6>
            </div>

        </div>
        <br>
        <br>
    </div>
    </div>
    <div class="tmain">
        <h3 style="font-size:30px;"><?= session('comp_name') ?></h3>
        <h3 style="font-size:15px;margin-top:-25px;">Address: <?= session('comp_add') ?></h3>
        <p style="font-size:15px;">Mobile: <?= session('comp_mobile') ?> &#160;&#160; Email:
            <?= session('comp_email') ?></p>
        <hr>
        <table id="customers">
            <thead>
                <tr>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">#</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Date</th>

                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Bill No.</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Period</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Site</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Amount</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">User</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Location</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Remark</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Status</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $count = 1;
                    $row_count = 0;
                    $page = 1;
                @endphp
                @if (count($bills) > 0)
                    @foreach ($bills as $bill)
                        @php
                            $page_break = false;
                            $row_required = count($bill->items) + 3;

                            if ($page == 1) {
                                $total_row = 18;
                                $avail_row = $total_row - $row_count;
                                if ($avail_row < $row_required) {
                                    $page_break = true;
                                    $row_count = 0;
                                    $page++;
                                }
                            } else {
                                $total_row = 30;
                                $avail_row = $total_row - $row_count;
                                if ($avail_row < $row_required) {
                                    $page_break = true;
                                    $row_count = 0;
                                    $page++;
                                }
                            }
                        @endphp
                        @if ($page_break)
                            <tr style="page-break-before: always;"></tr>

                        @endif
                        <tr>
                        <td rowspan="{{ count($bill->items) + 2 }}">{{ $count++ }}</td>
                        <td rowspan="{{ count($bill->items) + 2 }}">{{ $bill->billdate }}</td>

                        <td rowspan="{{ count($bill->items) + 2 }}">{{ $bill->bill_no }}</td>
                        <td>{{ $bill->bill_period }}</td>
                        <td>{{ $bill->site_name }}</td>
                        <td style="font-weight:bold;">{{ $bill->amount }}</td>
                        <td>{{ $bill->user_name }}</td>

                        <td>{{ $bill->location }}</td>
                        <td>{{ $bill->remark }}</td>
                        @if ($bill->status == 'Pending')
                            <td rowspan="{{ count($bill->items) + 2 }}" style="color:orange;">{{ $bill->status }}</td>
                        @elseif($bill->status == 'Rejected')
                            <td rowspan="{{ count($bill->items) + 2 }}" style="color:red;">{{ $bill->status }}</td>
                        @else
                            <td rowspan="{{ count($bill->items) + 2 }}" style="color:green;">{{ $bill->status }}</td>
                        @endif


                        </tr>
                        @php
                        $row_count++;
                        @endphp
                        @php
                            $count2 = 1;
                        @endphp
                        @if (count($bill->items) > 0)
                            <tr>

                                <th style="border:2px solid {{ session()->get('primary_color')[0] }}; color:black;">#
                                </th>
                                <th style="border:2px solid {{ session()->get('primary_color')[0] }}; color:black;">
                                    Work</th>
                                <th style="border:2px solid {{ session()->get('primary_color')[0] }}; color:black;">
                                    Unit</th>
                                <th style="border:2px solid {{ session()->get('primary_color')[0] }}; color:black;">
                                    Rate</th>
                                <th style="border:2px solid {{ session()->get('primary_color')[0] }}; color:black;">QTY
                                </th>
                                <th style="border:2px solid {{ session()->get('primary_color')[0] }}; color:black;">
                                    Amount</th>




                            </tr>
                            @php
                            $row_count++;
                            @endphp

                            @foreach ($bill->items as $item)
                                <tr>

                                    <td
                                        style="border:2px solid {{ session()->get('primary_color')[0] }};     text-align: center;">
                                        {{ $count2++ }}</td>

                                    <td
                                        style="border:2px solid {{ session()->get('primary_color')[0] }};     text-align: center;">
                                        {{ $item->work_name }}</td>
                                    <td
                                        style="border:2px solid {{ session()->get('primary_color')[0] }};     text-align: center;">
                                        {{ $item->unit }}</td>

                                    <td
                                        style="border:2px solid {{ session()->get('primary_color')[0] }};     text-align: center;">
                                        {{ $item->rate }}</td>
                                    <td
                                        style="border:2px solid {{ session()->get('primary_color')[0] }};     text-align: center;">
                                        {{ $item->qty }}</td>
                                    <td
                                        style="border:2px solid {{ session()->get('primary_color')[0] }}; font-weight:bold;     text-align: center;">
                                        {{ $item->amount }}</td>


                                </tr>
                                @php
                                $row_count++;
                                @endphp

                            @endforeach
                            <tr>
                                <th style="border:none;"></th>



                                <th style="border:none;"></th>
                                <th style="border:none;"></th>
                                <th style="border:none;"></th>
                                <th style="border:none;"></th>
                                <th style="border:none;"></th>

                                <th style="border:none;"></th>
                                <th style="border:none;"></th>
                                <th style="border:none;"></th>
                                <th style="border:none;"></th>

                            </tr>
                            @php
                            $row_count++;
                            @endphp
                        @endif
                    @endforeach
                @else
                    <tr>
                        <td colspan="3">No bills found</td>

                    </tr>
                @endif
            </tbody>

        </table>

    </div>

    </div>

</body>

</html>
