<table>
    <tr>
        <td colspan="7" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:20px; font-weight:bold;" colspan="4"
            rowspan="1">
            Asset Site Report
            <br>
            Site Name : {{$site_name}}


        </td>

        <td style="background-color: {{ $color }}; color:white; padding-top:10px;" colspan="3" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
          

        </td>


    </tr>


    <tr>
        <td colspan="7" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:17px; font-weight:bold;"
            colspan="7" rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="7" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="7" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="7" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Name</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Head</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Cost Price</th>

        <th
            style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Status</th>

        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            At Current Site</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Purchase Date</th>

    </tr>
    @php
        $count = 0;
    @endphp
    @if (count($data) > 0)
     
        @foreach ($data as $dat)         
            <tr>
                <td>{{ ++$count }}</td>
                <td>{{ $dat->name }}</td>
                <td>{{ $dat->head }}</td>
                <td>
                    @if ($dat->status == 'Sold')
                        Cost Price - {{ $dat->cost_price }}<br>
                        Sale Price - {{ $dat->sale_price }}
                    @else
                        {{ $dat->cost_price }}
                    @endif
                </td>
                <td>{{ $dat->status }}</td>
            
                <td>
                    @if ($dat->status != 'Sold')
                    {{ getAssetLastTransfer($dat->id)->create_datetime }}
                    @else
                        Already sold
                    @endif
                </td>

                <td> {{ $dat->create_datetime }}
                </td>
            </tr>
        @endforeach
    @endif
</table>
