<html>

<head>
    <style>
        .sub {
            display: flex;
            /* align-items: center; */
            justify-content: space-between;
            color: white;
            place-content: space-between;
        }

        .half-div1 {
            margin-left: 20px;
            margin-right: 20px;
            width: 35%;
            display: inline-block;
            vertical-align: top;
        }

        .half-div2 {
            margin-left: 20px;
            margin-right: 20px;
            width: 45%;
            display: inline-block;
            vertical-align: top;
        }


        h4,
        h6 {
            margin: 0;
        }

        .row {
            display: flex;
            justify-content: space-between;
            border-bottom: 1px solid #ccc;
            padding: 8px 0;
        }

        .header {
            font-weight: bold;
        }




        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
            padding-bottom: 30px;

        }

        #customers td,
        #customers th {
            border: 1.5px solid black;
            font-size: 5px;
            padding: 8px;
        }


        #customers th {

            padding-top: 12px;
            padding-bottom: 12px;
            text-align: center;

            color: white;
        }

        .tmain {
            background-color: white;
            margin: 10px;

            padding: 2px;
            border-radius: 25px;
        }

        .hmain {
            color: white;
            font-size: 25px;
            margin-top: -20px;
        }

        h3 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        hr {
            height: 1.5px;
            width: 90%;
            background-color: black;
            margin-bottom: 30px;

        }
    </style>
</head>

<body style="background-color:{{ session()->get('primary_color')[0] }}; border-radius: 25px;">



    <div class="hmain">
        <h3 style="font-size:40px;">Payment Voucher Report</h3>
        <p style="margin-top:-30px;">Party Name : {{ $partyname['party_status']->name }}</p>
        <p style="margin-top:-25px;">Party Type : {{ $partyname['type'] }}</p>
        <p style="margin-top:-20px;">Site Name : {{ $sitename }}</p>
        <div class="sub">
            <div class="half-div1" style="float:left;">
                <h6>Report Generated From </h6>
                <h4><u><a href="https://constructionmunshi.com/" target="_blank" style="color:white;">Construction
                            Munshi</a></u></h4>

            </div>
            <div class="half-div2" style="float:right;">
                <h6>Report Generated On: <?= date('d-m-Y') ?> </h6>
                <h6>Report Generated By: <?= session('name') ?> </h6>
                <h6>Report Period : {{ $start_date }} - {{ $end_date }}</h6>
            </div>

        </div>
        <br>
        <br>
    </div>
    </div><br>
    <div class="tmain">
        <h3 style="font-size:30px;"><?= session('comp_name') ?></h3>
        <h3 style="font-size:15px;margin-top:-25px;">Address: <?= session('comp_add') ?></h3>
        <p style="font-size:15px;">Mobile: <?= session('comp_mobile') ?> &#160;&#160; Email:
            <?= session('comp_email') ?></p>
        <hr>
        <table id="customers">
            <thead>
                <tr>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">#</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Date</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Voucher No.</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Company</th>

                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Amount</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Status</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Created By</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Approved By</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Paid By</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Payment Details</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Payment Date</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Remark</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">Image/s</th>
                </tr>
            </thead>
            <tbody>
                @php $count =1;@endphp
                @if (count($data) > 0)

                    @foreach ($data as $dat)
                        <tr>
                            <td>{{ $count++ }}</td>
                            <td>{{ $dat->date }}</td>
                            <td>{{ $dat->voucher_no }}</td>
                            <td>{{ $dat->company_name }}</td>


                            <td>{{ $dat->amount }}</td>
                            @if ($dat->status == 'Pending')
                                <td style="color:orange;">{{ $dat->status }}</td>
                            @elseif($dat->status == 'Rejected')
                                <td style="color:red;">{{ $dat->status }}</td>
                            @elseif($dat->status == 'Approved')
                                <td style="color:blue;">{{ $dat->status }}</td>
                            @elseif($dat->status == 'Paid')
                                <td style="color:green;">{{ $dat->status }}</td>
                            @endif
                            <td>{{ $dat->created_user }}</td>
                            <td>{{ $dat->approved_user }}</td>
                            <td>{{ $dat->paid_user }}</td>
                            <td>{{ $dat->payment_details }}</td>
                            <td>{{ $dat->payment_date }}</td>
                            <td>{{ $dat->remark }}</td>



                            <td>
                                @if ($dat->image != null)
                                    <a href="<?= attachmentUrl($dat->image) ?>">View Image</a>
                                @endif
                                @if ($dat->payment_image != null)
                                    <a href="<?= attachmentUrl($dat->payment_image) ?>">View Payment Image</a>
                                @endif
                            </td>




                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="3">No dats found</td>

                    </tr>
                @endif
            </tbody>

        </table>

    </div>

    </div>

</body>

</html>
