<table>
    <tr>
        <td colspan="11" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:20px; font-weight:bold;" colspan="5"
            rowspan="1">
            Expense Report
        

        </td>
        <td style="background-color: {{$color}}; color:white;"colspan="6" rowspan="1">

        </td>
    </tr><tr>
        <td style="background-color: {{$color}};  color:white; font-size:18px; font-weight:bold;" colspan="5"
        rowspan="1">
        
       Site Name - <?= $sitename?>

    </td>
    <td style="background-color: {{$color}}; color:white;"colspan="1" rowspan="1">

    </td>
        <td style="background-color: {{$color}}; color:white; padding-top:10px;" colspan="5" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
            Report Period : {{ $start_date }} - {{ $end_date }}
         

        </td>


    </tr>

    <tr>
        <td colspan="11" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:17px; font-weight:bold;" colspan="11"
            rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="11" rowspan="1">
            Address : <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="11" rowspan="1">
            Mobile : <?= session('comp_mobile') ?> E-mail : <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="11" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Date</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Party Name</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Head</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Particular</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Amount</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">User</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Location</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Remark</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Status</th>
        <th style="background-color:{{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Image</th>
    </tr>
    @php
        $count = 0;
    @endphp
    @foreach ($Expenses as $exp)
        <tr>
            <td>{{ ++$count }}</td>
            <td>{{ $exp->date }}</td>
            <td>{{ $exp->party_name }}</td>
            <td>{{ $exp->head_name }}</td>
            <td>{{ $exp->particular }}</td>
            <td  style="font-weight:bold;" >{{ $exp->amount }}</td>
            <td>{{ $exp->user_name }}</td>
            <td>{{ $exp->location }}</td>
            <td>{{ $exp->remark }}</td>
            @if ($exp->status == 'Pending')
                <td style="color:orange;">{{ $exp->status }}</td>
            @elseif($exp->status == 'Rejected')
                <td style="color:red;">{{ $exp->status }}</td>
            @else
                <td style="color:green;">{{ $exp->status }}</td>
            @endif
            @if($exp->image != "images/expense.png")
            <td><a href="<?= attachmentUrl($exp->image) ?>">View Image</a></td>
            @else
            <td></td>
            @endif
        </tr>
    @endforeach
</table>
