<html>

<head>
    <style>
        .sub {
            display: flex;
            /* align-items: center; */
            justify-content: space-between;
            color: white;
            place-content: space-between;
        }

        .half-div {
            margin-left: 20px;
            margin-right: 20px;
            width: 40%;
            display: inline-block;
            vertical-align: top;
        }


        h4,
        h6 {
            margin: 0;
        }

        .row {
            display: flex;
            justify-content: space-between;
            border-bottom: 1px solid #ccc;
            padding: 8px 0;
        }

        .header {
            font-weight: bold;
        }




        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
            padding-bottom: 30px;

        }

        #customers td,
        #customers th {
            border: 1.5px solid black;
            font-size: 6px;
            padding: 8px;
        }


        #customers th {

            padding-top: 12px;
            padding-bottom: 12px;
            text-align: center;

            color: white;
        }

        .tmain {
            background-color: white;
            margin: 10px;

            padding: 2px;
            border-radius: 25px;
        }

        .hmain {
            color: white;
            font-size: 25px;
            margin-top: -20px;
        }

        h3 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        hr {
            height: 1.5px;
            width: 90%;
            background-color: black;
            margin-bottom: 30px;

        }
    </style>
</head>

<body style="background-color:{{ session()->get('primary_color')[0] }}; border-radius: 25px;">



    <div class="hmain">
        <h3 style="font-size:40px;">Machinery Service Report</h3>
       
        <div class="sub">
            <div class="half-div" style="float:left;">
                <h6>Report Generated From </h6>
                <h4><u><a href="https://constructionmunshi.com/" target="_blank" style="color:white;">Construction
                            Munshi</a></u></h4>

            </div>
            <div class="half-div" style="float:right;">
                <h6>Report Generated On: <?= date('d-m-Y') ?> </h6>
                <h6>Report Generated By: <?= session('name') ?> </h6>
                <h6>Report Period : {{ $start_date }} - {{ $end_date }}</h6>
            </div>

        </div>
        <br>
        <br>
        <br>
    </div>
    </div>
    <div class="tmain">
        <h3 style="font-size:30px;"><?= session('comp_name') ?></h3>
        <h3 style="font-size:15px;margin-top:-25px;">Address: <?= session('comp_add') ?></h3>
        <p style="font-size:15px;">Mobile: <?= session('comp_mobile') ?> &#160;&#160; Email:
            <?= session('comp_email') ?></p>
        <hr>
        <table id="customers">
            <thead>
                <tr>

                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        #
                    </th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Name</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Head</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Date</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        User</th>
            
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Maintenance Items</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Next Service</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Remark</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Attachment 1</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Attachment 2</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Attachment 3</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Attachment 4</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Attachment 5</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $count = 0;

                @endphp
                @if (count($data) > 0)
                    @php
                        $machine = $data[0]->machinery_id;
                    @endphp

                    @foreach ($data as $dat)
                        @if ($dat->machinery_id != $machine)
                            @php $machine=$dat->machinery_id; @endphp
                            <tr>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                                <td style="background-color:black;"></td>
                            </tr>
                        @endif
                        <tr>
                            <td>{{ ++$count }}</td>
                            <td>{{ $dat->machine_name }}</td>
                            <td>{{ $dat->head_name }}</td>
                            <td>{{ $dat->create_date }}</td>
                            <td>{{ $dat->user_name }}</td>
                            <td>{{ $dat->maintainence_item }}</td>
                            <td>{{ $dat->next_service_on }}</td>
                            <td>{{ $dat->remark }}</td>
                            <td>
                                @if($dat->image1 != "N/A")                    
                                <a href="<?= attachmentUrl($dat->image1) ?>">View Attachment</a>
                            @endif
                            </td>
            
                            <td>
                                @if($dat->image2 != "N/A")                    
                                <a href="<?= attachmentUrl($dat->image2) ?>">View Attachment</a>
                            @endif
                            </td>
            
            
                            <td>
                                @if($dat->image3 != "N/A")                    
                                <a href="<?= attachmentUrl($dat->image3) ?>">View Attachment</a>
                            @endif
                            </td>
            
                            <td>
                                @if($dat->image4 != "N/A")                    
                                <a href="<?= attachmentUrl($dat->image4) ?>">View Attachment</a>
                            @endif
                            </td>
            
                            <td>
                                @if($dat->image5 != "N/A")                    
                                <a href="<?= attachmentUrl($dat->image5) ?>">View Attachment</a>
                            @endif
                            </td>
            
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="9">No data found</td>

                    </tr>
                @endif
            </tbody>

        </table>

    </div>

    </div>

</body>

</html>
