<table>
    <tr>
        <td colspan="{{ $column_count }}" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:20px; font-weight:bold;"
            colspan="{{ ceil($column_count / 2) }}" rowspan="1">
            Sales Report


        </td>
        <td style="background-color: {{ $color }}; color:white;"colspan="{{ floor($column_count / 2) }}"
            rowspan="1">

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:18px; font-weight:bold;"
            colspan="{{ ceil($column_count / 2) }}" rowspan="1">

            Financial Year - <?= $financial_year ?><br>
            Head Name - <?= $head_name ?>

        </td>

        <td style="background-color: {{ $color }}; color:white; padding-top:10px;"
            colspan="{{ floor($column_count / 2) }}" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>


        </td>


    </tr>

    <tr>
        <td colspan="{{ $column_count }}" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:17px; font-weight:bold;"
            colspan="{{ $column_count }}" rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="{{ $column_count }}" rowspan="1">
            Address : <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="{{ $column_count }}" rowspan="1">
            Mobile : <?= session('comp_mobile') ?> E-mail : <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="{{ $column_count }}" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <th style="background-color:{{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        @foreach ($heads as $head)
            <th
                style="background-color:{{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
                {{ $head }}
            </th>
        @endforeach
    </tr>
    @php
        $count = 0;
    @endphp
    @foreach ($body as $data)
        <tr>
            <td>{{ ++$count }}</td>
            @foreach ($data as $dat)
                <td>{{ $dat }}</td>
            @endforeach
        </tr>
    @endforeach
</table>
