<html>

<head>
    <style>
        .sub {
            display: flex;
            /* align-items: center; */
            justify-content: space-between;
            color: white;
            place-content: space-between;
        }

        .half-div {
            margin-left: 20px;
            margin-right: 20px;
            width: 40%;
            display: inline-block;
            vertical-align: top;
        }


        h4,
        h6 {
            margin: 0;
        }

        .row {
            display: flex;
            justify-content: space-between;
            border-bottom: 1px solid #ccc;
            padding: 8px 0;
        }

        .header {
            font-weight: bold;
        }




        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
            padding-bottom: 30px;

        }

        #customers td,
        #customers th {
            border: 1.5px solid black;
            font-size: 6px;
            padding: 8px;
        }


        #customers th {

            padding-top: 12px;
            padding-bottom: 12px;
            text-align: center;

            color: white;
        }

        .tmain {
            background-color: white;
            margin: 10px;

            padding: 2px;
            border-radius: 25px;
        }

        .hmain {
            color: white;
            font-size: 25px;
            margin-top: -20px;
        }

        h3 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        hr {
            height: 1.5px;
            width: 90%;
            background-color: black;
            margin-bottom: 30px;

        }
    </style>
</head>

<body style="background-color:{{ session()->get('primary_color')[0] }}; border-radius: 25px;">



    <div class="hmain">
        <h3 style="font-size:40px;">Asset Sale Report</h3>

        <div class="sub">
            <div class="half-div" style="float:left;">
                <h6>Report Generated From </h6>
                <h4><u><a href="https://constructionmunshi.com/" target="_blank" style="color:white;">Construction
                            Munshi</a></u></h4>

            </div>
            <div class="half-div" style="float:right;">
                <h6>Report Generated On: <?= date('d-m-Y') ?> </h6>
                <h6>Report Generated By: <?= session('name') ?> </h6>
                <h6>Report Period : {{ $start_date }} - {{ $end_date }}</h6>
            </div>

        </div>
        <br>
        <br>
        <br>
    </div>
    </div>
    <div class="tmain">
        <h3 style="font-size:30px;"><?= session('comp_name') ?></h3>
        <h3 style="font-size:15px;margin-top:-25px;">Address: <?= session('comp_add') ?></h3>
        <p style="font-size:15px;">Mobile: <?= session('comp_mobile') ?> &#160;&#160; Email:
            <?= session('comp_email') ?></p>
        <hr>
        <table id="customers">
            <thead>
                <tr>

                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        #
                    </th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Date</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Name</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Head Name</th>
                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Sale Site</th>

                    <th style="background-color:{{ session()->get('secondry_color')[0] }};">
                        Amount</th>
                </tr>
            </thead>
            <tbody>
                @php $count =0;@endphp
                @if (count($data) > 0)

                    @foreach ($data as $dat)
                        <tr>
                            <td>{{ ++$count }}</td>
                            <td>{{ $dat->sale_date }}</td>
                            <td>{{ $dat->name }}</td>
                            <td>{{ $dat->head_name }}</td>
                            <td>{{ $dat->sale_site }}</td>
                            <td style="font-weight:bold;">{{ $dat->sale_price }}</td>




                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="3">No data found</td>

                    </tr>
                @endif
            </tbody>

        </table>

    </div>

    </div>

</body>

</html>
