<table>
    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:20px; font-weight:bold;" colspan="5"
            rowspan="1">
            Material Supplier Statement
            <br>
            Supplier Name : {{ $party_name }}
        </td>
        <td style="background-color: {{ $color }}; color:white; padding-top:10px;" colspan="5" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
        </td>
    </tr>
    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white; font-size:17px; font-weight:bold;"
            colspan="10" rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="10" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{ $color }};  color:white;" colspan="10" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="10" rowspan="1" style="background-color: {{ $color }};"></td>
    </tr>
    <tr>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">#
        </th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Date</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Ref</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Ref No.</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            User</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Site</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Credit</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Debit</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Particular</th>
        <th style="background-color: {{ $sec_color }}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            Image</th>
    </tr>
    @php $count =0;@endphp
    @if (count($data) > 0)

        @foreach ($data as $dat)
            <tr>
                <td>{{ ++$count }}</td>
                <td style="font-weight:bold;">{{ $dat['date'] }}</td>
                <td>{{ $dat['ref'] }}</td>
                <td>{{ $dat['ref_no'] }}</td>
                <td>{{ $dat['user_name'] }}</td>
                <td>{{ $dat['site_name'] }}</td>
                <td style="font-weight:bold;">{{ $dat['credit'] }}</td>
                <td style="font-weight:bold;">{{ $dat['debit'] }}</td>
                <td>{{ $dat['particular'] }}</td>
                <td>
                    @if ($dat['image'] != '' && $dat['image'] != null && $dat['image'] != 'images/expense.png')
                        <a href="<?= attachmentUrl($dat['image']) ?>">View Image</a>
                    @endif
                </td>


            </tr>
        @endforeach
        <tr>
            <td></td>
            <td style="font-weight:bold;"></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Total</td>
            <td style="font-weight:bold;">{{ $total_credit }}</td>
            <td style="font-weight:bold;">{{ $total_debit }}</td>
            <td></td>
            <td></td>


        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td> </td>
            <td></td>
            <td>Closing Balance</td>
            <td style="font-weight:bold;">{{ $partybalance }}</td>


        </tr>
    @else
        <tr>
            <td colspan="3">No Transaction Found</td>

        </tr>
    @endif
</table>
